server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vc_db?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&character_set_server=UTF-8
    username: admin
    password: admin
    initialization-mode: always
  jpa:
    show-sql: false
    # Allows Hibernate to generate SQL optimized for a particular DBMS
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL5Dialect
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true

